app_name: dozer-ingest-users
version: 1
connections:
  - config: !Grpc
      schemas: !Path "config/events.json"
      port: 7001
    name: ingest

sources:
  - name: events
    table_name: events
    connection: ingest

sql: |
  SELECT id, temperature
  INTO alerts
  FROM events
  WHERE temperature >= 23.0

endpoints:
  - name: events
    path: /events
    table_name: events

  - name: alerts
    path: /alerts
    table_name: alerts
