app_name: kafka-transactions
cache_max_map_size: 8589934592
api:
  internal:
    port: 50052
    host: "[::1]"
  rest:
    port: 8088
connections:
  - config : !Kafka
      broker: localhost:19092
      schema_registry_url: http://localhost:18081
    name: kafka_store


sql: |
  SELECT
    t.id,
    t.customer_id,
    t.amount,
    t.location,
    t.provider
  INTO tout
  FROM transactions t;

sources:
  - name: transactions
    table_name: transactions
    connection: !Ref kafka_store
    columns:

endpoints:
  - name: tout
    path: /tout
    table_name: tout
    index:
      primary_key:

telemetry:
  metrics: !Prometheus
