connections:    
  - config : !LocalStorage
      details:
        path: data
      tables:
        - !Table
          name: trips
          config: !Parquet
            path: trips
            extension: .parquet
    name: ny_taxi

sql: |
  SELECT t.VendorID AS vendor, ROUND(SUM(t.trip_distance), 2) AS total_distance
  INTO total_distance
  FROM trips t
  GROUP BY t.VendorID;

sources:
  - name: trips
    table_name: trips
    connection: !Ref ny_taxi
    columns:

endpoints:
  - name: total_distance
    path: /total_distance
    table_name: total_distance
    index:
      primary_key: 

