version: 1
app_name: dozer-chinook-mysql

connections:
  - name: chinook_mysql
    config: !MySQL
      url: "{{MYSQL_URL}}"

sources:
  - name: employee
    table_name: Employee
    connection: chinook_mysql

  - name: invoice
    table_name: Invoice
    columns:
      - InvoiceId
      - CustomerId
      - InvoiceDate
      - Total
    connection: chinook_mysql

endpoints:
  - name: employee
    path: /employee
    table_name: employee

  - name: invoice
    path: /invoice
    table_name: invoice
