app_name: flight-microservices
connections:
  - config: !Postgres
      user: postgres
      password: postgres
      host: 0.0.0.0
      port: 5437
      database: flights
    name: bookings_conn
  - config: !Postgres
      user: postgres
      password: postgres
      host: 0.0.0.0
      port: 5437
      database: flights
    name: flights_conn

sources:
  - name: tickets
    table_name: tickets
    columns:
    connection: !Ref bookings_conn

  - name: bookings
    table_name: bookings
    columns:
    connection: !Ref bookings_conn

endpoints:
  - name: tickets
    path: /tickets
    table_name: tickets
    primary_key:
      - book_ref

  - name: bookings
    path: /bookings
    table_name: bookings
    index:
      primary_key:
        - book_ref

commit_size: 1
app_buffer_size: 1
