version: 1
app_name: simple-pg-sample
connections:
  - name: pagila_conn
    config: !Postgres
      user: "{{ POSTGRES_USER }}"
      password: "{{ POSTGRES_PASSWORD }}"
      host: "{{ POSTGRES_HOST }}"
      port: 5432
      database: "{{ POSTGRES_DATABASE }}"

sources:
  - name: actors
    table_name: actor
    connection: pagila_conn
  - name: films
    table_name: film
    connection: pagila_conn
    columns:
      - film_id
      - title

endpoints:
  - name: actors
    path: /actors
    table_name: actors

  - name: films
    path: /films
    table_name: films
