app_name: nested-trips
cache_max_map_size: 8589934592
connections:
  - config: !Dozer
      grpc:
        host: 0.0.0.0
        ## Default port of upstream dozer internal grpc server
        port: 50053
    name: nested_dozer

# Assigning different ports to not conflict with upstream dozer
api:
  rest:
    port: 7002
  grpc:
    port: 7003
  app_grpc:
    port: 7004

endpoints:
  - name: nested_trips_cache
    path: /nested_trips
    table_name: trips_cache
