global:
  scrape_interval: 1s
  scrape_timeout: 1s

scrape_configs:
  - job_name: dozer
    metrics_path: /metrics
    static_configs:
      - targets:
          - "localhost:9000"
        labels:
          # DOZER MAGIC ID
          namespace: dcd24b33-9614-410a-8261-d212f4acf7f5
