version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: dozer-chinook-1
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: mysql
      MYSQL_DATABASE: Chinook
    volumes:
      - ./mysql:/var/lib/mysql
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql


volumes:
  mysql-data: