version: 1
app_name: pg-supabase-1M
home_dir: ./.dozer
cache_dir: ./.dozer/cache
cloud:
  app:
    instance_type: large
connections:
  - config: !Postgres
      user: "{{PG_USER}}"
      password: "{{PG_PASSWORD}}"
      host: "{{PG_HOST}}"
      port: 5432
      database: "{{PG_DB}}"
      sslmode: null
      connection_url: null
    name: flights_conn

sources:
  - name: tickets
    table_name: tickets
    connection: flights_conn

  - name: flights
    table_name: flights
    connection: flights_conn

  - name: ticket_flights
    table_name: ticket_flights
    connection: flights_conn

  - name: airports
    table_name: airports
    connection: flights_conn

sql: |
  select f.arrival_airport as airport, a.coordinates as coordinates, COUNT(t.ticket_no) as tickets
  INTO airports_count
  from tickets t
  join ticket_flights tf on t.ticket_no = tf.ticket_no
  join flights f on tf.flight_id = f.flight_id
  join airports a on f.arrival_airport = a.airport_code
  group by f.arrival_airport, a.coordinates;

  select extract(HOUR FROM f.window_start) as start, count(f.window_start) as dep_count
  INTO departures_count
  from TUMBLE(flights, scheduled_departure, '4 HOURS') f
  group by extract(HOUR FROM f.window_start)

endpoints:
  - name: tickets
    path: /bookings/tickets
    table_name: tickets
    index:
      primary_key:
        - ticket_no

  - name: flights
    path: /bookings/flights
    table_name: flights
    index:
      primary_key:
        - flight_id

  - name: airports
    path: /bookings/airports
    table_name: airports
    index:
      primary_key:
        - airport_code

  - name: ticket_flights
    path: /bookings/ticket_flights
    table_name: ticket_flights
    index:
      primary_key:
        - ticket_no
        - flight_id

  - name: airports_count
    path: /airports_count
    table_name: airports_count
    index:
      primary_key:
        - airport
        - coordinates

  - name: departures_count
    path: /departures_count
    table_name: departures_count
    index:
      primary_key:
        - start
