version: 1
app_name: local-supabase-sample
cache_max_map_size: 2147483648
connections:
  - config: !Postgres
      user: "{{SUPABASE_USER}}"
      password: "{{SUPABASE_PASSWORD}}"
      host: "{{SUPABASE_HOST}}"
      port: 5432
      database: "{{SUPABASE_DB}}"
    name: pg

sources:
  - name: zones
    table_name: zones
    connection: pg

sql: |
  SELECT * INTO zone_data FROM zones;

endpoints:
  - name: zone_data
    path: /zone_data
    table_name: zone_data
